version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    ports:
      - 50070:50070
      - 9000:9000
    environment:
      CLUSTER_NAME: hadoop_cluster
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    networks:
      - hadoop
    volumes:
      - ./archive:/data
      - ./init:/upload

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    depends_on:
      - namenode
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    networks:
      - hadoop

  pyspark:
    build: .
    image: my-pyspark-hadoop
    container_name: pyspark
    ports:
      - 8888:8888
    depends_on:
      - namenode
      - datanode
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - hadoop

networks:
  hadoop:
    driver: bridge
